name: kicad

on:
  push:
    paths:
      - "**.sch"
      - "**.kicad_pcb"
  pull_request:
    paths:
      - "**.sch"
      - "**.kicad_pcb"

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: nerdyscout/kicad-exports@v2.2
        with:
          # Required - kibot config file
          config: docs.kibot.yaml
          # optional - prefix to output defined in config
          dir: docs
          # optional - schematic file
          schema: "source/*.sch"
          # optional - PCB design file
          board: "source/*.kicad_pcb"
      - name: upload results
        uses: actions/upload-artifact@v2
        with:
          name: docs
          path: docs
  bom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: nerdyscout/kicad-exports@v2.2
        with:
          # Required - kibot config file
          config: .config/bom.kibot.yaml
          # optional - prefix to output defined in config
          dir: bom
          # optional - schematic file
          schema: "source/*.sch"
          # optional - PCB design file
          board: "source/*.kicad_pcb"
      - name: upload results
        uses: actions/upload-artifact@v2
        with:
          name: bom
          path: bom
  gerbers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: nerdyscout/kicad-exports@v2.2
        with:
          # Required - kibot config file
          config: gerbers.kibot.yaml
          # optional - prefix to output defined in config
          dir: gerbers
          # optional - schematic file
          schema: "source/*.sch"
          # optional - PCB design file
          board: "source/*.kicad_pcb"
      - name: upload results
        uses: actions/upload-artifact@v2
        with:
          name: gerbers
          path: gerbers
  cad:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: nerdyscout/kicad-exports@v2.2
        with:
          # Required - kibot config file
          config: model.kibot.yaml
          # optional - prefix to output defined in config
          dir: model
          # optional - schematic file
          schema: "source/*.sch"
          # optional - PCB design file
          board: "source/*.kicad_pcb"
      - name: upload results
        uses: actions/upload-artifact@v2
        with:
          name: model
          path: model
